import { Bag } from "./bag";
export const BAGS: Bag[]=[
    {
        "id":"16",
        "cart":0,
        "name":"BAGS",
        "image":"/assets/img/bag1.jpg",
        "price":800,
        "category":"bag",
        "desc":"Bags"
    },
    {
        "id":"17",
        "cart":0,
        "name":"BAGS",
        "image":"/assets/img/bag2.jpg",
        "price":800,
        "category":"bag",
        "desc":"Bags"
    },
    {
        "id":"18",
        "cart":0,
        "name":"BAGS",
        "image":"/assets/img/bag3.jpg",
        "price":600,
        "category":"bag",
        "desc":"Bags"
    },
    {
        "id":"19",
        "cart":0,
        "name":"BAGS",
        "image":"/assets/img/bag4.jpg",
        "price":800,
        "category":"bag",
        "desc":"Bags"
    },
    {
        "id":"20",
        "name":"BAGS",
        "cart":0,
        "image":"/assets/img/bag5.jpg",
        "price":200,
        "category":"bag",
        "desc":"Bags"
    },
    {
        "id":"21",
        "cart":0,
        "name":"BAGS",
        "image":"/assets/img/bag5.jpg",
        "price":240,
        "category":"bag",
        "desc":"Bags"
    }
    ]